# Site settings
title: Silvio Relli
email: silvio@relli.it
url: https://relli.it
description: "Silvio Relli - Software developer, Ruby on Rails, Javascript, React"
keywords: "Ruby on Rails, Javascript, React, JS"
skills: "Software Developer"
meta_author: Silvio Relli

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
# http://www.colourlovers.com/palette/46688/fresh_cut_day
# color:
#   primary: FDF23E # giallo
#   secondary: AEE239 # verde
#   secondary-dark: 8FBE00 # verde scuro
#   tertiary: FF3D84 # rosa

# http://www.colourlovers.com/digital-art/trends/branding/7784/StAr_I.D.
color:
  primary: C6DAA2 # verde
  secondary: ECE6A4 # giallo
  secondary-dark: ECE6A4 # giallo
  tertiary: 444 # nero


# http://www.colourlovers.com/palette/159853/Pink_Parrot
# sfondo giallo (FDF23E) e scritte rosa (FF3D84)
# sfondo verde (AEE239) e scritte rosa (FF3D84)
# sfondo rosa (FF3D84) e scritte verdi (AEE239)

# Footer settings
footer:
  copyright: Silvio Relli
  location: Florence, Italy
  social: "Keep in touch!"
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/silviorelli/
  - title: github
    url: http://github.com/silviorelli
  - title: stack-overflow
    url: https://stackoverflow.com/users/1406791/silvio-relli
  - title: twitter
    url: https://twitter.com/silviorelli
  - title: facebook
    url: https://facebook.com/silviorelli
  - title: instagram
    url: https://www.instagram.com/silviorelli/


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
